name: "bluebell"
mode: "dev"
port: 8080
version: "v0.1.2"
start_time: "2024-04-12"
machine_id: 1

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_conns: 200
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100